version: '3'
services:
  memories_app-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mongodb
    ports:
      - 27017:27017
 memories_app-frontend:
    image: memories_app1:latest
    environment:
      PORT: 3000
      PROXY_API: http://localost:5000/
    ports:
      - 3000:3000
  playground-web-backend:
    image: backend:latest
    environment:
      MONGODB_URI: mongodb://playground-web-db:27017/playground-web
    ports:
      - 5000:5000